---
name: Build Image
on:
  push:
    branches:
      - '*'
  pull_request:
    branches: [master]

jobs:
  build:
    env:
      DEBIAN_FRONTEND: noninteractive
      DEBCONF_NONINTERACTIVE_SEEN: true
    runs-on: ubuntu-20.04
    steps:
      - name: Update repolist
        run: sudo apt-get update
      - name: Install dependencies
        run: sudo apt-get -y install systemd-container libarchive-dev libcurl4-openssl-dev libgpgme-dev meson ninja-build
      - name: Setting up python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install mkosi
        run: |
          python -m pip install --upgrade pip
          python -m pip install wheel
          python -m pip install git+https://github.com/systemd/mkosi.git
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v2.3.2
        with:
          submodules: recursive
      - name: Build pacman
        working-directory: pacman
        run: |
          mkdir build
          cd build
          meson --prefix=/usr \
                --buildtype=plain \
                -Ddoc=disabled \
                -Duse-git-version=true \
                -Dscriptlet-shell=/usr/bin/bash \
                -Dldconfig=/usr/bin/ldconfig \
          ..
          ninja
      - name: Install pacman
        working-directory: pacman
        run: |
          pushd build
          sudo ninja install
          popd
          wget -O makepkg.conf 'https://aur.archlinux.org/cgit/aur.git/plain/makepkg.conf?h=pacman-git'
          wget -O pacman.conf.x86_64 'https://aur.archlinux.org/cgit/aur.git/plain/pacman.conf.x86_64?h=pacman-git'
          sudo install -m644 pacman.conf.x86_64 /etc/pacman.conf
          sudo install -m644 makepkg.conf /etc
          sudo sed -i /etc/makepkg.conf \
                   -e "s|@CARCH[@]|x86_64|g" \
                   -e "s|@CHOST[@]|x86_64-pc-linux-gnu|g" \
                   -e "s|@CARCHFLAGS[@]|-march=x86-64|g"
      - name: Create Image
        run: sudo "$(type -P mkosi)"
      - name: Upload Image Artifact
        uses: actions/upload-artifact@v2
        with:
          name: kiwi-host.img
          path: kiwi-host.img
