---
name: Build Image
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    env:
      DEBIAN_FRONTEND: noninteractive
      DEBCONF_NONINTERACTIVE_SEEN: true
    runs-on: ubuntu-20.04
    steps:
      - name: Update repolist
        run: sudo apt-get update
      - name: Install dependencies
        run: sudo apt-get -y install debootstrap fakechroot systemd-container
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v2.3.2
      - name: Create Image
        run: sudo ./create-image.sh
      - name: Upload Image Artifact
        uses: actions/upload-artifact@v2
        with:
          name: kiwi-host.img
          path: kiwi-host.img
